### ISSUE TITLE
Tags

### ISSUE THREAD

**Issue by MarcelGarus** [candy-lang/candy#282]
Instead of symbols, we want to have tags that can also have an optional associated value. Our current symbols will just be named tags. Tags without an associated value can be called just like functions to associate a value with them.

```candy
tagWithoutValue = Foo
tagWithValue = Foo 3
newResult = Ok 4
error = Error "That didn't work."
dynamicallyCreatedTag = tagWithoutValue 5
nestedTag = Foo (Bar 3)
```

**Comment by JonasWanke** [comment]
Builtin functions we could offer:

```candy
tagGetSymbol # tag -> tagWithoutValue
tagHasValue  # tag -> bool
tagGetValue  # tag -> valueOrPanic
```

These would be exposed in `Core` as `tag.getSymbol`, `tag.hasValue`, and `tag.getValue`. Once we convert `result` to use tags instead of structs, we could even get rid of `structHasKey` and return a result in `structGet`.

We could also offer `tag.withSymbol` and `tag.withValue` to create a copy with the symbol or value replaced, respectively, that are based on the three builtin functions from above. But we can wait for destructuring support so that implementing them is cleaner
